version: '2.1'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html

  php:
    image: lcidral/yii2.php:7.2.2-fpm-alpine3.7
    restart: always
    depends_on:
      - nginx-proxy
    links:
      - mariadb
    volumes:
      - ~/.composer/cache:/root/.composer/cache
      - ./:/var/www/html
      - ./build/conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./build/conf/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./build/conf/php/docker-php-ext-sendmail.ini:/usr/local/etc/php/conf.d/docker-php-ext-sendmail.ini
      - ./build/conf/php/ssmtp.conf:/etc/ssmtp/ssmtp.conf
    environment:
      APP_MYSQL_HOST: '${DB_HOST}'
      APP_MYSQL_DBNAME: '${DB_NAME}'
      APP_MYSQL_USERNAME: '${DB_USERNAME}'
      APP_MYSQL_PASSWORD: '${DB_PASSWORD}'

  api:
    image: nginx:1.13.3-alpine
    restart: always
    ports:
      - "8083:80"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./build/conf/nginx/conf/api.conf:/etc/nginx/conf.d/api.conf:rw
      - ./build/conf/nginx/logs:/var/log/nginx
    environment:
      VIRTUAL_HOST: '${VIRTUAL_HOST_API}'

  mariadb:
    image: mariadb:10.1.26
    volumes:
      - "/tmp/.mysql-data:/var/lib/mysql"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      VIRTUAL_HOST: '${DB_HOST}'
      MYSQL_ROOT_PASSWORD: 'admin'
